import { LineageView } from "@/components/lineage-view";
import { Sidebar } from "@/components/sidebar";


export default function LineagePage() {
  return (
    <main className="app-shell">
      <div className="frame">
        <header className="topbar">
          <div className="brand">
            <div className="brand-mark" />
            <div className="brand-copy">
              <h1>LakeForge</h1>
              <p>Lineage workspace</p>
            </div>
          </div>
          <div className="status-pill">Lineage view active</div>
        </header>

        <div className="layout">
          <Sidebar activeItem="Lineage" />
          <section className="content">
            <div className="hero">
              <article className="card">
                <p className="eyebrow">Lineage Surface</p>
                <h2>First source-to-target catalog view</h2>
                <p className="muted">
                  This page shows persisted lineage edges generated by pipeline runs, which gives us
                  the first catalog-style view of how notebooks and pipelines write to managed targets.
                </p>
              </article>

              <article className="card">
                <p className="eyebrow">What It Covers</p>
                <h3>Notebook and pipeline write lineage</h3>
                <p className="muted">
                  It is intentionally lightweight, but it brings us closer to the real Databricks DE
                  operating model where lineage and data quality are part of the daily workflow.
                </p>
              </article>
            </div>

            <LineageView />
          </section>
        </div>
      </div>
    </main>
  );
}
